FROM schoolofdevops/maven:spring as build

WORKDIR /app

COPY .  .

RUN mvn spring-javaformat:apply && \
    mvn package -DskipTests && \
    mv target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar /run/petclinic.jar

CMD java  -jar /run/petclinic.jar



FROM openjdk:11
COPY --from=build target/*.jar  /app/target/*.jar
RUN javac Main.java
CMD ["java", "Main"]